version: '3.8'

services:
         nm:
                build:
                      context: .
                      dockerfile: Dockerfile
                container_name: nm-development
                volumes:
                        -        nm_vol:/app
                restart:        always
volumes:
        nm_vol:
                driver: local
                driver_opts:
                        type: none
                        device: /Users/tariqelb/docker-bind-volume/nm
                        o: bind
networks:
         nm-net:
                 name: nm-net
